# Generated by Django 3.2 on 2024-07-17 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Пользователь может использовать только буквы, цифры и @/./+/-/_ символы.', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
